version: "3"
services:
  node-docker:
    build:
      context: ./
      args:
        NODE_ENV: dev
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
